# Copyright 2024 The Brax Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Proximal policy optimization training.

See: https://arxiv.org/pdf/1707.06347.pdf
"""

import flax
import jax
import jax.numpy as jnp
from brax.training.types import Params


@flax.struct.dataclass
class SafePPONetworkParams:
    """Contains training state for the learner."""

    policy: Params
    value: Params
    cost_value: Params


def compute_gae(
    truncation: jnp.ndarray,
    termination: jnp.ndarray,
    rewards: jnp.ndarray,
    values: jnp.ndarray,
    bootstrap_value: jnp.ndarray,
    lambda_: float = 1.0,
    discount: float = 0.99,
):
    """Calculates the Generalized Advantage Estimation (GAE).

    Args:
      truncation: A float32 tensor of shape [T, B] with truncation signal.
      termination: A float32 tensor of shape [T, B] with termination signal.
      rewards: A float32 tensor of shape [T, B] containing rewards generated by
        following the behaviour policy.
      values: A float32 tensor of shape [T, B] with the value function estimates
        wrt. the target policy.
      bootstrap_value: A float32 of shape [B] with the value function estimate at
        time T.
      lambda_: Mix between 1-step (lambda_=0) and n-step (lambda_=1). Defaults to
        lambda_=1.
      discount: TD discount.

    Returns:
      A float32 tensor of shape [T, B]. Can be used as target to
        train a baseline (V(x_t) - vs_t)^2.
      A float32 tensor of shape [T, B] of advantages.
    """

    truncation_mask = 1 - truncation
    # Append bootstrapped value to get [v1, ..., v_t+1]
    values_t_plus_1 = jnp.concatenate(
        [values[1:], jnp.expand_dims(bootstrap_value, 0)], axis=0
    )
    deltas = rewards + discount * (1 - termination) * values_t_plus_1 - values
    deltas *= truncation_mask

    acc = jnp.zeros_like(bootstrap_value)
    vs_minus_v_xs = []

    def compute_vs_minus_v_xs(carry, target_t):
        lambda_, acc = carry
        truncation_mask, delta, termination = target_t
        acc = delta + discount * (1 - termination) * truncation_mask * lambda_ * acc
        return (lambda_, acc), (acc)

    (_, _), (vs_minus_v_xs) = jax.lax.scan(
        compute_vs_minus_v_xs,
        (lambda_, acc),
        (truncation_mask, deltas, termination),
        length=int(truncation_mask.shape[0]),
        reverse=True,
    )
    # Add V(x_s) to get v_s.
    vs = jnp.add(vs_minus_v_xs, values)

    vs_t_plus_1 = jnp.concatenate([vs[1:], jnp.expand_dims(bootstrap_value, 0)], axis=0)
    advantages = (
        rewards + discount * (1 - termination) * vs_t_plus_1 - values
    ) * truncation_mask
    return jax.lax.stop_gradient(vs), jax.lax.stop_gradient(advantages)


def make_losses(
    ppo_network,
    clipping_epsilon,
    entropy_cost,
    reward_scaling,
    discounting,
    gae_lambda,
    normalize_advantage,
    cost_scaling,
    safety_budget,
    safety_discounting,
    safety_gae_lambda,
    use_disagreement,
    adaptive_budget_horizon=False,
    budget_decision_steps=None,
):
    def compute_policy_loss(
        policy_params,
        value_params,
        cost_value_params,
        normalizer_params,
        data,
        penalizer,
        penalizer_params,
        key,
    ):
        parametric_action_distribution = ppo_network.parametric_action_distribution
        policy_apply = ppo_network.policy_network.apply
        value_apply = ppo_network.value_network.apply
        data = jax.tree_util.tree_map(lambda x: jnp.swapaxes(x, 0, 1), data)
        policy_logits = policy_apply(normalizer_params, policy_params, data.observation)
        baseline = value_apply(normalizer_params, value_params, data.observation)
        terminal_obs = jax.tree_util.tree_map(lambda x: x[-1], data.next_observation)
        bootstrap_value = value_apply(normalizer_params, value_params, terminal_obs)
        rewards = data.reward * reward_scaling
        truncation = data.extras["state_extras"]["truncation"]
        termination = (1 - data.discount) * (1 - truncation)
        target_log_probs = parametric_action_distribution.log_prob(
            policy_logits, data.extras["policy_extras"]["raw_action"]
        )
        behavior_log_probs = data.extras["policy_extras"]["log_prob"]
        _, advantages = compute_gae(
            truncation=truncation,
            termination=termination,
            rewards=rewards,
            values=baseline,
            bootstrap_value=bootstrap_value,
            lambda_=gae_lambda,
            discount=discounting,
        )
        if normalize_advantage:
            advantages = (advantages - advantages.mean()) / (advantages.std() + 1e-8)
        rho_s = jnp.exp(target_log_probs - behavior_log_probs)
        surrogate1 = rho_s * advantages
        surrogate2 = (
            jnp.clip(rho_s, 1 - clipping_epsilon, 1 + clipping_epsilon) * advantages
        )
        policy_loss = -jnp.mean(jnp.minimum(surrogate1, surrogate2))
        entropy = jnp.mean(parametric_action_distribution.entropy(policy_logits, key))
        entropy_loss = -entropy_cost * entropy
        aux = {
            "policy_loss": policy_loss,
            "entropy_loss": entropy_loss,
        }
        if penalizer is not None:
            cost_value_apply = ppo_network.cost_value_network.apply
            cost = data.extras["state_extras"]["cost"] * cost_scaling
            if use_disagreement:
                disagreement = data.extras["state_extras"]["disagreement"]
                cost += disagreement
            cost_baseline = cost_value_apply(
                normalizer_params, cost_value_params, data.observation
            )
            cost_bootstrap_value = cost_value_apply(
                normalizer_params, cost_value_params, terminal_obs
            )
            vsc, cost_advantages = compute_gae(
                truncation=truncation,
                termination=termination,
                rewards=cost,
                values=cost_baseline,
                bootstrap_value=cost_bootstrap_value,
                lambda_=safety_gae_lambda,
                discount=safety_discounting,
            )
            negative_cost_advantages = -cost_advantages
            if normalize_advantage:
                negative_cost_advantages = (
                    negative_cost_advantages - negative_cost_advantages.mean()
                ) / (negative_cost_advantages.std() + 1e-8)
            surrogate1_cost = rho_s * negative_cost_advantages
            surrogate2_cost = (
                jnp.clip(rho_s, 1 - clipping_epsilon, 1 + clipping_epsilon)
                * negative_cost_advantages
            )
            cost_advantages = -jnp.minimum(surrogate1_cost, surrogate2_cost)
            cumulative_cost = data.extras["state_extras"]["cumulative_cost"]
            if use_disagreement:
                disagreement = data.extras["state_extras"]["disagreement"]
                cumulative_cost += disagreement
            # ---- THE BUDGET IS A RATE, AND WITHOUT THIS IT PENALISES SPEED --
            #
            # `safety_budget` arrived here already normalised in train.py as
            #     (B / num_decision_steps) / (1 - safety_discounting)
            # where num_decision_steps is the EPISODE-LENGTH CAP (2500//4 = 625).
            # For a steady per-decision cost c the cost critic saturates at
            # vsc = c/(1-safety_discounting), so `constraint >= 0` reduces
            # exactly to `c <= B / 625` -- a RATE that must hold in every state,
            # not a total that must hold over an episode.
            #
            # That is fine while every episode runs to the cap. It stops being
            # fine under `terminate_on_goal`, which is default-on for the ants:
            # a policy that crosses and stops runs ~123 decisions, so its real
            # allowance is 123 * B/625 = 0.20 B, while a policy that loiters to
            # the cap is allowed the full B. Same flag, 5x different real
            # budget, and THE ONE DOING THE TASK GETS LESS. Measured on the
            # 2026-08-26 budget-30 pair: CRPO settled at 0.63 m of an 11 m
            # corridor and Lagrangian at 0.85 m, both with episodes stretched
            # back out toward the cap. Loitering was the rational answer to the
            # constraint as posed, and both algorithms found it.
            #
            # With adaptive_budget_horizon the denominator becomes the episode
            # length the batch ACTUALLY shows, so allowance * length == B for
            # every policy and the incentive disappears.
            #
            # ESTIMATOR: termination and truncation are (T, N) indicators of an
            # episode ending, so their mean is the per-decision probability of
            # an ending and its reciprocal is the mean episode length. No new
            # extra_fields plumbing -- both are already computed above for GAE.
            #
            # It is deliberately CLAMPED to [1, budget_decision_steps]: an
            # episode can never exceed the cap, and a batch in which nothing
            # ends (early training, before the ant reaches the goal at all)
            # gives end_rate 0, which then degrades exactly to the fixed
            # behaviour rather than dividing by zero.
            budget = safety_budget
            mean_ep_decisions = jnp.asarray(
                budget_decision_steps if budget_decision_steps else 1.0,
                dtype=jnp.float32,
            )
            if adaptive_budget_horizon:
                if not budget_decision_steps:
                    raise ValueError(
                        "adaptive_budget_horizon needs budget_decision_steps "
                        "(the episode-length cap in decisions) to clamp against"
                    )
                end_rate = jnp.mean(termination + truncation)
                mean_ep_decisions = jnp.clip(
                    1.0 / jnp.maximum(end_rate, 1e-8), 1.0, float(budget_decision_steps)
                )
                # safety_budget was normalised against the CAP; rescale it onto
                # the observed length. cap/mean >= 1, so this only ever LOOSENS
                # the per-decision rate -- the episode TOTAL it permits is
                # unchanged at B, which is the whole point.
                budget = safety_budget * (
                    float(budget_decision_steps) / mean_ep_decisions
                )
            constraint = budget - vsc.mean()
            policy_loss, penalizer_aux, _ = penalizer(
                policy_loss,
                constraint,
                jax.lax.stop_gradient(penalizer_params),
                rest=-cost_advantages.mean(),
            )
            aux["normalized_constraint_estimate"] = constraint
            aux["budget_mean_episode_decisions"] = mean_ep_decisions
            aux["budget_effective_rate"] = budget * (1.0 - safety_discounting)
            aux["cumulative_costs"] = cumulative_cost.max(0).mean()
            aux |= penalizer_aux
        total_loss = policy_loss + entropy_loss
        return total_loss, aux

    def compute_value_loss(params, normalizer_params, data):
        value_apply = ppo_network.value_network.apply
        data = jax.tree_util.tree_map(lambda x: jnp.swapaxes(x, 0, 1), data)
        baseline = value_apply(normalizer_params, params, data.observation)
        terminal_obs = jax.tree_util.tree_map(lambda x: x[-1], data.next_observation)
        bootstrap_value = value_apply(normalizer_params, params, terminal_obs)
        rewards = data.reward * reward_scaling
        truncation = data.extras["state_extras"]["truncation"]
        termination = (1 - data.discount) * (1 - truncation)
        vs, _ = compute_gae(
            truncation=truncation,
            termination=termination,
            rewards=rewards,
            values=baseline,
            bootstrap_value=bootstrap_value,
            lambda_=gae_lambda,
            discount=discounting,
        )
        v_error = vs - baseline
        v_loss = jnp.mean(v_error**2) * 0.25
        return v_loss, {"v_loss": v_loss}

    def compute_cost_value_loss(params, normalizer_params, data):
        cost_value_apply = ppo_network.cost_value_network.apply
        data = jax.tree_util.tree_map(lambda x: jnp.swapaxes(x, 0, 1), data)
        cost = data.extras["state_extras"]["cost"] * cost_scaling
        if use_disagreement:
            disagreement = data.extras["state_extras"]["disagreement"]
            cost += disagreement
        cost_baseline = cost_value_apply(normalizer_params, params, data.observation)
        terminal_obs = jax.tree_util.tree_map(lambda x: x[-1], data.next_observation)
        cost_bootstrap = cost_value_apply(normalizer_params, params, terminal_obs)
        truncation = data.extras["state_extras"]["truncation"]
        termination = (1 - data.discount) * (1 - truncation)
        vcs, _ = compute_gae(
            truncation=truncation,
            termination=termination,
            rewards=cost,
            values=cost_baseline,
            bootstrap_value=cost_bootstrap,
            lambda_=safety_gae_lambda,
            discount=safety_discounting,
        )
        cost_error = vcs - cost_baseline
        cost_v_loss = jnp.mean(cost_error**2) * 0.25
        return cost_v_loss, {"cost_v_loss": cost_v_loss}

    return compute_policy_loss, compute_value_loss, compute_cost_value_loss
